apiVersion: v1
kind: Service
metadata:
  name: digest-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: digest   
---
apiVersion: batch/v1
kind: Job
metadata:
  name: digest
spec:
  template:
    metadata:
      labels:
        app: digest
    spec:
      restartPolicy: Never
      containers:
      - name: digest
        image:  guymforer/datadigest
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_PASSWORD
          value: MosheForer97
        - name: POSTGRES_DB
          value: tweets 
        - name: POSTGRES_USER
          value: postgres
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config  
              key: url